// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8MT8yQzk0UkkUPFOyFCV1OqXaxGU8ZI',
    appId: '1:762333574328:web:39d7958e134a2b6471f04d',
    messagingSenderId: '762333574328',
    projectId: 'fir-pipeline-d056d',
    authDomain: 'fir-pipeline-d056d.firebaseapp.com',
    storageBucket: 'fir-pipeline-d056d.appspot.com',
    measurementId: 'G-NWPZQ942PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hG1bDlAFJSPRuUsm-tqXu7sjxrCaHmI',
    appId: '1:762333574328:android:a9889f8f1c32b84d71f04d',
    messagingSenderId: '762333574328',
    projectId: 'fir-pipeline-d056d',
    storageBucket: 'fir-pipeline-d056d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-polhX5osJeN7H_WfX4SwxNulC3UeIcM',
    appId: '1:762333574328:ios:6567cdd14bd1e42e71f04d',
    messagingSenderId: '762333574328',
    projectId: 'fir-pipeline-d056d',
    storageBucket: 'fir-pipeline-d056d.appspot.com',
    iosClientId: '762333574328-rgdirq6d27uu11h7ek2kro67o99d5vr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoPipeline',
  );
}
