trigger:
  - master

pool:
  vmImage: "macos-latest"

variables:
  - group: secrets
  - group: general
  - name: androidReleaseDir
    value: $(build.artifactStagingDirectory)/build/app/outputs/flutter-apk
  - name: apkFile
    value: $(androidReleaseDir)/app-release.apk

jobs:
  - job: DemoPipelineAndroidDev
    displayName: "Demo Pipeline android dev"
    workspace:
      clean: all
    steps:
      - template: "build.yml"
      - template: "release.yml"